### PR TITLE
Add associations 3

### PR DESCRIPTION
**Pull request by calebbourg**
try associations

### CODE REVIEW

**Comment by sellis7** [comment]
I'm a bit confused... so the second PR (#11) is really the same as this one, but now has associations added? If that's the case, perhaps the first PR should be deleted, and the second one (this one) merged. 

I would suggest inquiring of Kevin how he thinks we should proceed with this. I'm quite unsure myself.

**Comment by calebbourg** [comment]
the reason we did it this way was because we had finalized the actual models and migrations on sunday as a group. Uma and I were unsure about how the associations would work so we decided to split the pull requests up so that we could establish the models without associations and then have the group review the associations before merging that pull request. Maybe it was a confusing way of doing it :/ apologies.

**Comment by hkawanishi** [comment]
If we merge pull request (#11)(first one), and then merge pull request (#12)(second one), should it work?  If we want to keep it simple, we can just remove (#11) pull request, and don't worry about including association part.  If we decide that we need to change the association part, we can change those files later.

**Comment by sellis7** [comment]
I think I understand. The pull request isn't really necessary to make until you're sure that your branch and all its commits are ready to be attached to the master, so that's why I didn't understand the one pull request following the other. But you also had created 2 different branches for each of these, too, right? So, one branch was sorta a copy of the other, but just used to add the "associations" - do I have that right?

Also, the build didn't pass because there's an error on one of the models. If you follow the error message (click on the Codeship link for the build), it'll tell you what file and on what line. If you struggle to locate it, let me know and I'll help you out.  :)

**Comment by sellis7** [comment]
I can't db:migrate because I get the same error message, and can't view my local development environment now. Since I've a bit to keep working on so I don't hold everyone up on their tasks, I'm going to just repair the migration file locally.

Should a decision be made to merge the current PR (#12), to incorporate the associations, the error will still be there until my eventual PR is made and merged to master. Just a heads up to anyone who is pulling locally to work on their bits to this puzzle.

**Pull request merged**
