### PR TITLE
Install devise

### PR DESCRIPTION
**Pull request by PYLiao**
install gem 'devise'

create model 'User'

### CODE REVIEW

**Comment by disciplesofld** [comment]
I had inquired of everyone in Slack, but there's been so much activity that I think it was missed: since we're implementing Devise, and it uses forms, did everyone want to also have the Simple Form gem installed since we've been using that since the beginning of the program? Otherwise, the forms for Devise will be coded slightly different than we're used to. Though, if Devise is already installed, we will have to modify all the user forms now. Just to keep in mind...

**Comment by umasenthil** [comment]
Simple form sounds good to me. We can stick to whatever we have used so far to keep it simple.

Date: Wed, 30 Dec 2015 06:10:13 -0800

**Comment by PYLiao** [comment]
Sorry I missed the message in slack. Does that mean gem Simple Form has to be installed before Devise? If so, we can ignore this pull request, and I can create other pull request, which is install Simple form first, then create another pull request for Devise.

**Comment by sellis7** [comment]
It's ok, and not surprising that it got missed. I'm having a hard time keeping up with all of it, myself. If Devise was already installed, we'll just have to modify the forms that it automatically generates in all the Devise files, once the Simple Form gem is installed. I did the same thing myself when creating my Flixter app. It's not a big deal... just a bit of copy/pasting that will need to happen.

**Comment by PYLiao** [comment]
Cool. So we can still merge this pull request. I just find a post which is talking about the situation.

"If, like me, you had already generated the Devise views before installing SimpleForm, you'll need to re-generate the views after installing SimpleForm by running rails generate devise:views. If you would see few conflicts with files then you should just rewrite them."

Follow by the blog, after install Simple Form I just need to regenerate the views for the devise.

**Comment by sellis7** [comment]
There you go.... I'd "like" or give you a "thumbs up" on your last comment, if I could. :+1: (ha! I found I could!) Yeah - it's not a big deal to modify it. Whoever want to merge this, go for it! I am going to pull all the newly modified/updated code locally, then, and push my first commit to GitHub that will establish the linked CI, and you'll all get an email shortly with the details. \o/ (Yea!)

**Comment by PYLiao** [comment]
Thanks Sherilyn :)

**Comment by sellis7** [comment]
I merged the PR Po-Yang opened... everything looked a-ok. I'm going to add the gems Simple Form & Rubocop to our budding app as another branch and create another PR. If anyone gets the chance to look that over later and wants to merge it, that would be awesome. Then when the app is up-to-date, I'll wrap up any issues with Codeship automatically deploying to Heroku, to be sure all that is functional.

**Pull request merged**
